  
# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: wso2-ei-observability
description: Helm chart for installing WSO2 Enterprise Integrator observability profile
type: application
version: 1.0.0
appVersion: 7.1.0
home: https://wso2.com/integration/
sources:
  - https://github.com/wso2/micro-integrator
  - https://github.com/wso2/wso2-synapse
  - https://github.com/wso2/carbon-mediation
maintainers:
  - name: tishan89
    email: tishan@wso2.com
dependencies:
  - name: prometheus-statsd-exporter
    version: 0.15.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 8.5.1
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
    condition: loki-stack.enabled
  - name: jaeger-operator
    version: 2.56.0
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled

