{
 "title": "WSO2 Integration Cluster Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "Displays the number of nodes connected to this cluster",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_server_up)"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Displays the number of services deployed in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(service_name,service_type)(wso2_integration_service_up))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Node List",
   "type": "table-old",
   "description": "Displays nodes that are deployed in this cluster",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (wso2_integration_server_up>0)*1000"
    }
   ]
  },
  {
   "title": "Service List",
   "type": "table-old",
   "description": "Displays services that are deployed in this cluster",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max by(service_name,service_type) (wso2_integration_service_up>0)*1000",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "description": "Displays the total request count served by the cluster for the selected time period. Request which resulted in errors will be counted here too.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_total\"}[$__range]))- (min_over_time({__name__ =~\"wso2_integration_.*_request_count_total\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays the total error count occurred in this cluster for the selected time period",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\"}[$__range]))- (min_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Displays the request rate received by cluster during the selected time period. This will also include error requests. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_total\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "Displays the error rate occurred at this cluster during the selected time period. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_error_total\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "Displays 95th and 50th percentile of response times served by all nodes of this cluster",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", le=~\".+\"}[10m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", le=~\".+\"}[10m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Displays the logs(carbon.log) of this node during the selected time period. If no log entries were logged during the selected time pane will be empty.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{log_level=\"ERROR\"}"
    }
   ]
  }
 ]
}